version: "3"
services:
  amqp:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/conf.d/10-defaults.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - poc
networks:
  poc:
    external: 
      name: poc