version: "3"
services:
  db:
    image: postgres
    container_name: 'db_receive_to_send'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - poc
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - poc
networks:
  poc:
    external: 
      name: poc